repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
        
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-case-conflict

-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
    -   id: poetry-check

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
    -   id: check-github-workflows
    -   id: check-dependabot

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--strict", "--ignore-missing-imports", "--pretty"]
        exclude: '^(.*\/tests\/.*|tests\/.*|.*\/tests\.py)$'
        require_serial: true

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-xvs", "tests/"]
